### PR TITLE
Correct statement about maxsnew/lazy

### PR DESCRIPTION
**Pull request by jvoigtlaender**

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Ah, you were too quick to merge. Actually listing this under "What is now in elm-community?" doesn't make much sense anymore. It's still true that the statement as written was wrong. But the correct answer should go elsewhere, I guess.

**Comment by fredcy** [comment]
Good point. I'll fix that.

**Comment by fredcy** [comment]
Meta comment: My plan with managing PRs on elm-faq is to merge quickly and fix afterward if necessary. If someone consistently submits PRs that need fixing then theirs won't be merged so quickly in the future.

**Comment by jvoigtlaender** [comment]
Fair enough.

**Pull request merged**
